# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='auth_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='auth_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
